version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "habitusnet/platform-engineering"
    assignees:
      - "habitusnet/platform-engineering"
    open-pull-requests-limit: 5
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    reviewers:
      - "habitusnet/platform-engineering"
    assignees:
      - "habitusnet/platform-engineering"
    open-pull-requests-limit: 5