version: 0.1
cli:
  version: 1.22.15
plugins:
  sources:
    - id: trunk
lint:
  enabled:
    - actionlint@1.6.26
    - checkov@3.2.26
    - eslint@9.27.0
    - markdownlint@0.39.0
    - osv-scanner@1.6.2
    - prettier@3.5.3
    - shellcheck@0.9.0
    - shfmt@3.6.0
    - trufflehog@3.63.7
    - yamllint@1.33.0
  threshold:
    - linters: [ALL]
      level: high
actions:
  enabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available